fails:self.send(:block_given?) always returns false
